### ISSUE TITLE
XRLaser, XRProximity, XRTeleport tags need to be added to project.

### ISSUE THREAD

**Issue by rygo6** [Fjordnet/UnityLIB-XRInteraction#1]

**Comment by fjordchrism** [comment]
When a project containing XRInteraction is first loaded, these tags should be automatically added to the Tags list.

**Comment by fjordchrism** [comment]
Added PR #6 to add these tags when project is loaded in the editor and they don't appear in TagManager list @rygo6 .

**Comment by fjordchrism** [comment]
Merged in #6.
